### ISSUE TITLE
Request to guide about how to include issue templates on github repository without showing on the repository file list

### ISSUE THREAD

**Issue by alexcurrann** [talboren/gpt-dnd-game#5]
Hello sir,

I was trying to add issue templates to my github repository without showing the .github/issue_templates on my repository file list, as you have done for your repositories.
I have tried many different things, e.g., by using gitignore file or by .git/info/exclude, but could not do it as you have done it.
Can you please guide me of how can i achieve the same functionality for issue_templates.

**Comment by talboren** [comment]
Still need help with that, @alexcurrann?

**Comment by alexcurrann** [comment]
> Still need help with that, @alexcurrann?

No, i figured out how to do it, still thank you for reaching back
